"""add learning

Revision ID: 4da1783f1a68
Revises: 5472e472d155
Create Date: 2026-01-09 16:20:44.369581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4da1783f1a68'
down_revision: Union[str, Sequence[str], None] = '5472e472d155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learnings_id'), 'learnings', ['id'], unique=False)
    op.create_index(op.f('ix_learnings_title'), 'learnings', ['title'], unique=False)
    op.create_table('learning_skill',
    sa.Column('learning_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['learning_id'], ['learnings.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('learning_id', 'skill_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learning_skill')
    op.drop_index(op.f('ix_learnings_title'), table_name='learnings')
    op.drop_index(op.f('ix_learnings_id'), table_name='learnings')
    op.drop_table('learnings')
    # ### end Alembic commands ###
